
version: '3.8'

services:
  lobby-server:
    image: ghcr.io/beyond-imagination/beyondworm-lobby-server:latest
    container_name: lobby-server
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
    restart: always

  game-server:
    image: ghcr.io/beyond-imagination/beyondworm-game-server:latest
    container_name: game-server
    ports:
      - "7200:7200"
    environment:
      - PORT=7200
      - LOBBY_SERVER_URL=http://lobby-server:8081
      - SERVER_PUBLIC_URL=${SERVER_PUBLIC_URL} # 이 값은 .env 파일에서 읽어옵니다.
      - SERVER_INTERNAL_URL=http://game-server:7200
      - CORS_ORIGIN=${CORS_ORIGIN} # 이 값은 .env 파일에서 읽어옵니다.
    depends_on:
      - lobby-server
    restart: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60 # 60초마다 새 이미지가 있는지 확인합니다.
    restart: always
