
version: '3.8'

services:
  lobby-server:
    image: ghcr.io/beyond-imagination/beyondworm-lobby-server:latest
    container_name: lobby-server
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS} # 이 값은 .env 파일에서 읽어옵니다.
    restart: always

  game-server:
    image: ghcr.io/beyond-imagination/beyondworm-game-server:latest
    container_name: game-server
    ports:
      - "7200:7200"
    environment:
      - PORT=7200
      - LOBBY_SERVER_URL=http://lobby-server:8081
      - SERVER_PUBLIC_URL=${SERVER_PUBLIC_URL} # 이 값은 .env 파일에서 읽어옵니다.
      - SERVER_INTERNAL_URL=http://game-server:7200
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS} # 이 값은 .env 파일에서 읽어옵니다.
    depends_on:
      - lobby-server
    restart: always
